## Tutorial 3


10/03/2019

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error

## EXERCICE 1 -  Matrix

In [2]:
A = [[1,-2],[3,0]]
B = [[4,4],[-1,1]]
C = [[7,0]]
D = [[-3,1]]

In [3]:
A = np.matrix(A)
B = np.matrix(B)
C = np.matrix(C)
D = np.matrix(D)

In [4]:
A * B

matrix([[ 6,  2],
        [12, 12]])

In [5]:
B * A

matrix([[16, -8],
        [ 2,  2]])

In [6]:
B * np.transpose(B)

matrix([[32,  0],
        [ 0,  2]])

In [7]:
np.transpose(B) * B

matrix([[17, 15],
        [15, 17]])

In [8]:
C * A

matrix([[  7, -14]])

In [9]:
B *np.transpose(D)

matrix([[-8],
        [ 4]])

In [10]:
from numpy.linalg import inv
inv(A)

matrix([[ 0.        ,  0.33333333],
        [-0.5       ,  0.16666667]])

## EXERCICE 2 - Multiple Linear Regression 


In [11]:
gestation = np.array([35,40,42,37])
smoke = np.array([1,0,1,0])
weight = np.array([2440,3226,3301,2729])

In [12]:
d = {'gestation':gestation , 'smoke': smoke,  'Weight': weight}
df = pd.DataFrame(d)
df

NameError: name 'pd' is not defined

#### By Hand 

In [ ]:
X = np.matrix([[35,1],[40,0],[42,1],[37,0]])
y=  np.matrix([[2440, 3226, 3301, 2729]])
step1 = np.transpose(X) * X

In [ ]:
leftpart = inv(step1)

In [ ]:
rightpart = np.transpose(X)* np.transpose(y)

In [ ]:
leftpart * rightpart

In [ ]:
yhat = 77.84*gestation-126.50*smoke

In [ ]:
xbar = x.mean()
ybar = y.mean()

In [ ]:
y = np.array([2440, 3226, 3301, 2729])

In [ ]:
## calculate the sum of squared deviations
St = sum((y-ybar)**2)
St

In [ ]:
## calculate the sum of squares of the errors
Sr = sum((y-yhat)**2)
Sr

In [ ]:
##coefficient of determination
R2 = 1-float(Sr/St)
R2

In [ ]:
X = df.drop(['Weight'], axis = 1)
y = df['Weight']

In [ ]:
reg = LinearRegression(fit_intercept = False)
reg.fit(X,y)

In [ ]:
reg.coef_

In [ ]:
r2 = round(reg.score(X, y),2)

print("The model performance for training set")
print("--------------------------------------")
print('R2 score is {}'.format(r2))
print("\n")

In [ ]:
plt.setp(g.get_legend().get_texts(), fontsize='22');
g=sns.scatterplot(x="gestation", y="Weight", hue="smoke", data=df);
g.set_xlabel("Gestation",fontsize=20)
g.set_ylabel("Weight",fontsize=20);

In [ ]:
data = pd.read_csv('birth-smoke.txt', sep='\t')
data.head()

- Response (y): birth weight (Weight) in grams of baby
- Potential predictor (x1): Smoking status of mother (yes or no)
- Potential predictor (x2): length of gestation (Gest) in weeks

In [ ]:
plt.setp(g.get_legend().get_texts(), fontsize='22');
g=sns.scatterplot(x="Gest", y="Wgt", hue="Smoke", data=data);
g.set_xlabel("Gestation",fontsize=20)
g.set_ylabel("Weight",fontsize=20);

In [ ]:
# encode the binary variable Smoke in 1 and 0 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.Smoke)

In [ ]:
list(le.classes_)

In [ ]:
le.transform(data.Smoke)

In [ ]:
data['Smoke_encode'] = le.transform(data.Smoke)

In [ ]:
data

In [ ]:
X = data.drop(['Wgt','Smoke'], axis = 1)
y = data['Wgt']

In [ ]:
reg = LinearRegression()
reg.fit(X,y)

In [ ]:
y_predict = reg.predict(X)
y_predict

In [ ]:
rmse = (np.sqrt(mean_squared_error(y, y_predict)))
r2 = round(reg.score(X, y),2)

print("The model performance is")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

## Case Study - Boston House Pricing



Source :
https://medium.com/@amitg0161/sklearn-linear-regression-tutorial-with-boston-house-dataset-cde74afd460a

In [ ]:
from sklearn import *
from sklearn.datasets import load_boston
import pandas as pd

In [ ]:
boston = load_boston()

In [ ]:
bos = pd.DataFrame(boston.data)
bos.columns = boston.feature_names
bos['PRICE'] = boston.target
print(bos.head())

- CRIM per capita crime rate by town

- ZN proportion of residential land zoned for lots over 25,000 sq.ft.

- INDUS proportion of non-retail business acres per town

- CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)

- NOX nitric oxides concentration (parts per 10 million)

- RM average number of rooms per dwelling

- AGE proportion of owner-occupied units built prior to 1940

- DIS weighted distances to five Boston employment centres

- RAD index of accessibility to radial highways

- TAX full-value property-tax rate per $10,000

- PTRATIO pupil-teacher ratio by town

- B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town

- LSTAT % lower status of the population

- MEDV Median value of owner-occupied homes in $1000’s

In [ ]:
print(bos.describe())

In [ ]:
sns.boxplot(bos.PRICE);
plt.title("Boxplot of the price")
plt.xlabel('')
plt.ylabel('');

In [ ]:
sns.set(rc={'figure.figsize':(11.7,8.27)})
corr = bos.corr()
sns.heatmap(corr, annot=True);
plt.title("Correlation Matrix");

In [ ]:
plt.figure(figsize=(20, 5))

features = ['LSTAT', 'RM', 'CRIM' ]
target = bos['PRICE']

for i, col in enumerate(features):
    plt.subplot(1, len(features) , i+1)
    x = bos[col]
    y = target
    plt.scatter(x, y, marker='o')
    plt.title("Variation in House prices")
    plt.xlabel(col)
    plt.ylabel('"House prices in $1000"')

### Linear regression Model with one variable

In [ ]:
X_rooms = bos.RM
y_price = bos['PRICE']

In [ ]:
X_rooms = np.array(X_rooms).reshape(-1,1)
y_price = np.array(y_price).reshape(-1,1)

print(X_rooms.shape)
print(y_price.shape)

In [ ]:
X_train_1, X_test_1, Y_train_1, Y_test_1 = train_test_split(X_rooms, y_price, test_size = 0.2, random_state=5)

print(X_train_1.shape)
print(X_test_1.shape)
print(Y_train_1.shape)
print(Y_test_1.shape)


In [ ]:
reg_1 = LinearRegression()
reg_1.fit(X_train_1, Y_train_1)

y_train_predict_1 = reg_1.predict(X_train_1)
rmse = (np.sqrt(mean_squared_error(Y_train_1, y_train_predict_1)))
r2 = round(reg_1.score(X_train_1, Y_train_1),2)

print("The model performance for training set")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

In [ ]:
## Plot the model fitted with a line
prediction_space = np.linspace(min(X_rooms), max(X_rooms)).reshape(-1,1) 
plt.scatter(X_rooms,y_price)
plt.plot(prediction_space, reg_1.predict(prediction_space), color = 'black', linewidth = 3)
plt.ylabel('value of house/1000($)')
plt.xlabel('number of rooms')
plt.show()


### Multiple Linear regression Model with all the data

In [ ]:
X = bos.drop('PRICE', axis = 1)
y = bos['PRICE']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

reg_all = LinearRegression()
reg_all.fit(X_train, y_train)

# model evaluation for training set

y_train_predict = reg_all.predict(X_train)
rmse = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
r2 = round(reg_all.score(X_train, y_train),2)

print("The model performance for training set")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

In [ ]:
reg_all.coef_

In [ ]:
reg_all.intercept_